### PR TITLE
All in issue

### PR DESCRIPTION
**Pull request by Identity-labs**
fix all-in with sharing remaining pot with all when player with small value than high bet follow win.

### CODE REVIEW

**Comment by Identity-labs** [comment]
You have found new way to do calculation ?

**Comment by ptwu** [comment]
> You have found new way to do calculation ?

Might be able to implement [this](https://softwareengineering.stackexchange.com/questions/317640/poker-split-side-pots/344835#344835), will try later

**Comment by ptwu** [comment]
Just implemented the algorithm and it looks like it handles all-in situations correctly from playtesting, but is not passing the tests

**Comment by Identity-labs** [comment]
You think bet stage can be wrong ? 
Because they say algo work perfectly

**Comment by ptwu** [comment]
> You think bet stage can be wrong ?
> Because they say algo work perfectly

The implementation here is different because I already subtract from player money during the round whenever bets are made. In the StackOverflow example, they have an `invested` field which keeps track of bets instead. I'm thinking my implementation strategy has a bug.

**Comment by Identity-labs** [comment]
You reset winnerPot in the first iteration loop

**Pull request closed without merging**
