### PR TITLE
Rewrite distribute money

### PR DESCRIPTION
**Pull request by Identity-labs**

### CODE REVIEW

**Comment by Identity-labs** [comment]
I have rewrite distributeMoney, with original algo in pure method calculateMoney can be tested independently
I dont have push on previous branch to keep your work
Still not perfect :
- Test all-in 3 players low credits win is not ok
- Test all-in 3 players low credits win seem to be ok

I have add test : Test _distributeMoney

**Comment by Identity-labs** [comment]
Ok, my friends have play a lot, money distribution is good :)
- "reveal" event don't have good winners send, with have to send winner after moneyCalculation to have good winner
- Issue not related, but if we are more than 2, all players follow blind, alter 2 players fold, the game is stuck.

I will handle reveal event, and I will try to find why game is stuck when all fold

**Comment by Identity-labs** [comment]
The 'Test all fold' as no issue, I don't a seen he have their own event to end the game "endHand"
The 'Test fold' as missing money in the end of the game, distributeMoney is never called I don't know why, it's the last issue

**Comment by Identity-labs** [comment]
@ptwu distribute money seem good to me,

We have last issue to fix, and it's perfect :
The 'Test fold' as missing money in the end of the game, distributeMoney is never called I don't know why, it's the last issue
So when 1 player fold, the money is lost at the end of the game

**Comment by ptwu** [comment]
> @ptwu distribute money seem good to me,
> 
> We have last issue to fix, and it's perfect :
> The 'Test fold' as missing money in the end of the game, distributeMoney is never called I don't know why, it's the last issue
> So when 1 player fold, the money is lost at the end of the game

Wow, thanks for all your work. I'll add you on Discord so we can talk, let me buy you a coffee or something for your help. 

I'll take a look after work tonight, I'm living in the USA so we seem to have different timezones.

**Comment by Identity-labs** [comment]
Shit I have ignore your invite before I see this message :) resend one :)
Yes I'm from France, I work with lot of people worldwide :)

**Comment by Identity-labs** [comment]
It's fix, I don't know how :), I have done step by step refactor.

**Pull request merged**
