### PR TITLE
Update test / But still not working

### PR DESCRIPTION
**Pull request by Identity-labs**

### CODE REVIEW

**Comment by Identity-labs** [comment]
The current player to play has the status "Their Turn" ?

**Comment by ptwu** [comment]
> The current player to play has the status "Their Turn" ?

Correct. Status can only be "Their Turn", "Fold", or the empty string.

**Comment by Identity-labs** [comment]
You can look quickly on that test to make it work ?
Like that we can add test on other issue, and fix them

**Comment by Identity-labs** [comment]
Test is working :)

**Comment by ptwu** [comment]
Just added CI that checks for tests passing. Thanks a lot, is this PR ready for review?

**Comment by Identity-labs** [comment]
Yes it's ready for review, I have fix some issues :)

**Comment by ptwu** [comment]
Also added you as a collaborator, feel free to create branches instead of working from forks if that is easier for you.

**Comment by Identity-labs** [comment]
Yes seems good to me.

**Pull request merged**
